# Generated by Django 3.2.6 on 2021-08-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productmanagement', '0004_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(related_name='products', to='Productmanagement.Product'),
        ),
    ]
